# Generated by Django 3.0.4 on 2020-10-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Doc',
            field=models.FileField(default='', upload_to='tasksfile/'),
        ),
    ]
